package synth

import (
	"errors"
	"testing"
)

// csv.Writer buffers into a 4096-byte bufio, so a header only reaches the sink
// when it is longer than that — which is exactly when a failing sink must be
// reported instead of leaving the caller with a silently truncated file. The
// field names are padded to get the header over the buffer; nothing else about
// them matters.
type wideHeaderRow struct {
	Column00PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column01PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column02PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column03PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column04PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column05PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column06PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column07PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column08PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column09PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column10PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column11PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column12PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column13PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column14PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column15PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column16PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column17PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column18PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column19PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column20PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column21PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column22PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column23PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column24PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column25PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column26PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column27PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column28PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column29PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column30PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column31PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column32PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column33PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column34PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column35PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column36PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column37PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column38PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column39PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column40PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column41PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column42PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column43PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column44PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column45PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column46PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column47PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column48PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column49PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column50PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column51PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column52PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column53PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column54PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column55PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column56PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column57PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column58PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column59PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column60PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column61PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column62PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column63PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column64PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column65PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column66PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column67PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column68PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column69PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column70PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
	Column71PaddedToMakeTheHeaderLongEnoughToOverflowTheBuffer string
}

func TestEncodeCSVHeaderErrorReachesCaller(t *testing.T) {
	err := encodeCSV(&failWriter{after: 0}, []wideHeaderRow{{}})
	if !errors.Is(err, errDisk) {
		t.Fatalf("encodeCSV = %v, want the sink's error", err)
	}
}
