package pgcopy

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/bakhod1r/synth/schema"
)

// pgColumn is one Postgres type, named the same way in both places it is
// needed: the CREATE TABLE and the binary encoder.
type pgColumn struct {
	name  string // the type as written in DDL
	oid   int    // the Postgres type OID
	width int    // encoded width in bytes, -1 for variable
}

// pgTypes maps a Go value type to the Postgres column that receives it.
//
// Binary COPY sends no type names, so the table's column types ARE the
// decoding instructions. This table is the single place both sides read from,
// which is what makes the data file and the generated DDL impossible to
// disagree.
var pgTypes = map[string]pgColumn{
	"string":    {"varchar", 1043, -1},
	"int64":     {"bigint", 20, 8},
	"float64":   {"double precision", 701, 8},
	"bool":      {"boolean", 16, 1},
	"time.Time": {"timestamp", 1114, 8},
}

// kindGoType names the kinds whose generated value is not a string. Synth has
// 250-odd kinds and all but these produce strings, so listing the exceptions
// is shorter and easier to keep true than listing the rule.
//
// pgcopy_kinds_test.go generates a value for every registered kind and checks
// this map against what actually came out, so a new kind cannot quietly land
// in the wrong column type.
var kindGoType = map[schema.Kind]string{
	schema.KindInt:         "int64",
	schema.KindAge:         "int64",
	schema.KindYear:        "int64",
	schema.KindUnixTime:    "int64",
	schema.KindPort:        "int64",
	schema.KindHTTPStatus:  "int64",
	schema.KindPercentage:  "int64",
	schema.KindSalary:      "int64",
	schema.KindTemperature: "int64",
	schema.KindFloat:       "float64",
	schema.KindTimeSeries:  "float64",
	schema.KindAmount:      "float64",
	schema.KindBalance:     "float64",
	schema.KindRating:      "float64",
	schema.KindLatitude:    "float64",
	schema.KindLongitude:   "float64",
	schema.KindBool:        "bool",
	schema.KindTime:        "time.Time",
	schema.KindBirthDate:   "time.Time",
}

// goTypeFor resolves the Go value type a field generates.
//
// The reflection frontend records it directly. The YAML, DDL, OpenAPI and
// Protobuf frontends do not — they only carry a kind — so the kind decides,
// and anything unrecognised is a string, which is what the overwhelming
// majority of kinds produce.
func goTypeFor(f schema.Field) string {
	if _, ok := pgTypes[f.GoType]; ok {
		return f.GoType
	}
	switch f.GoType {
	case "int", "int32", "int8", "int16":
		return "int64"
	case "float32":
		return "float64"
	case "uuid.UUID":
		return "string"
	}
	if t, ok := kindGoType[f.Kind]; ok {
		return t
	}
	return "string"
}

// columnType renders a field's Postgres column type, including the length when
// the source schema gave one.
func columnType(f schema.Field) string {
	col := pgTypes[goTypeFor(f)]
	if col.name != "varchar" {
		return col.name
	}
	if n, err := strconv.Atoi(f.Params["maxlen"]); err == nil && n > 0 {
		return fmt.Sprintf("varchar(%d)", n)
	}
	return "varchar"
}

// DDL renders the CREATE TABLE that receives the data file, followed by the
// COPY command that loads it.
//
// This exists because binary COPY is unusable without it: the file carries no
// type information, so a table built by hand that differs in any column is
// rejected outright — and the error arrives after the export has already been
// generated. Emitting both from the same type table removes the possibility.
func DDL(table string, s *schema.Schema, dataPath string, binary bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by synth. Load with:\n--   psql -f %s.sql\n", dataPath)
	fmt.Fprintf(&b, "CREATE TABLE %s (\n", quoteIdent(table))
	for i, f := range s.Fields {
		fmt.Fprintf(&b, "  %s %s", quoteIdent(f.Name), columnType(f))
		if f.PK {
			b.WriteString(" PRIMARY KEY")
		}
		if i < len(s.Fields)-1 {
			b.WriteByte(',')
		}
		b.WriteByte('\n')
	}
	b.WriteString(");\n\n")
	if binary {
		fmt.Fprintf(&b, "COPY %s FROM '%s' WITH (FORMAT binary);\n",
			quoteIdent(table), dataPath)
	} else {
		fmt.Fprintf(&b, "COPY %s FROM '%s';\n", quoteIdent(table), dataPath)
	}
	return b.String()
}

// quoteIdent always quotes. Column names come from someone else's schema and
// "order", "user" and "group" are ordinary column names that are also reserved
// words; quoting unconditionally is simpler than keeping a list of them
// correct.
func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}
